# Generated by Django 5.2.1 on 2025-09-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
        ('eventos', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['evento__data', 'nome'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterUniqueTogether(
            name='atividade',
            unique_together={('evento', 'nome')},
        ),
    ]
