# Generated by Django 5.2.1 on 2025-08-17 18:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('capacidade', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('tema', models.CharField(max_length=200)),
                ('horario', models.TimeField()),
            ],
            options={
                'verbose_name': 'Palestrante',
                'verbose_name_plural': 'Palestrantes',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('conferencia', 'Conferência'), ('workshop', 'Workshop'), ('festa', 'Festa'), ('exposicao', 'Exposição')], default='conferencia', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vagas_disponiveis', models.PositiveIntegerField(default=0)),
                ('imagem', models.URLField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.local')),
                ('palestrantes', models.ManyToManyField(blank=True, related_name='eventos', to='eventos.palestrante')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago'), ('promocional', 'Promocional')], default='pago', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='eventos.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='eventos.participante')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'unique_together': {('evento', 'participante')},
            },
        ),
    ]
