# Generated by Django 5.2.1 on 2025-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20250917_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capacidade',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='ativo', max_length=20),
        ),
    ]
