# Generated by Django 5.2.1 on 2025-09-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_criador_palestrante_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
