# Generated by Django 5.2.1 on 2025-09-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='palestrantes',
        ),
        migrations.DeleteModel(
            name='Palestrante',
        ),
    ]
