# Generated by Django 5.2.1 on 2025-09-02 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_remove_evento_palestrantes_delete_palestrante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('tema', models.CharField(max_length=200)),
                ('horario', models.TimeField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palestrante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Palestrante',
                'verbose_name_plural': 'Palestrantes',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='palestrantes',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='eventos.palestrante'),
        ),
    ]
