# Generated by Django 5.2.1 on 2025-09-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_palestrante_evento_palestrantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='palestrantes',
        ),
        migrations.DeleteModel(
            name='Palestrante',
        ),
    ]
