# Generated by Django 5.2.1 on 2025-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_remove_palestrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='vagas_disponiveis',
        ),
    ]
