# Generated by Django 5.2.1 on 2025-09-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_remove_evento_imagem_remove_evento_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='criador',
        ),
    ]
