# Generated by Django 5.2.1 on 2025-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, help_text='Área de atuação do palestrante', max_length=200, null=True),
        ),
    ]
