# Generated by Django 5.2.1 on 2025-09-06 12:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('V', 'VIP'), ('N', 'Normal'), ('E', 'Estudante'), ('G', 'Gratuito')], default='N', max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do ingresso em reais', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade_disponivel', models.PositiveIntegerField(help_text='Quantidade de ingressos disponíveis para venda', validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ingresso',
                'verbose_name_plural': 'Tipos de Ingressos',
                'ordering': ['evento__data', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gratuito', 'Gratuito'), ('pago', 'Pago'), ('promocional', 'Promocional')], default='pago', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
    ]
