# Generated by Django 5.2.1 on 2025-09-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('ingresso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoingresso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_ingressos', to='eventos.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='ingresso',
            unique_together={('evento', 'participante')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoingresso',
            unique_together={('evento', 'tipo')},
        ),
    ]
