# Generated by Django 5.2.1 on 2025-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0002_tipoingresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ingresso',
            name='data_compra',
        ),
    ]
