# Generated by Django 5.2.1 on 2025-09-09 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresso', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='data_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
