# Generated by Django 5.2.1 on 2025-09-02 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['nome'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterField(
            model_name='local',
            name='capacidade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
